# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://github.com

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: mvn clean package 
      working-directory: ./app
      run: mvn clean package
      
    - name: Run application in background
      working-directory: ./app
      run: |
        java -jar target/observability-app-0.0.1-SNAPSHOT.jar &
        sleep 15
        
    - name: Check endpoint
      run: curl -v http://localhost:8081
      
    - name: run the request all endpoint
      run: python3 req.py

      
    - name: run the request all endpoint Status Code
      run: python3 reqStaus.py
      
